theme: jekyll-theme-minimal
title: Sem-UBA
description: Introducci칩n a la programaci칩n en R para el an치lisis de datos en ciencias sociales (con orientaci칩n al estudio de conflictos y movimientos sociales)
logo: https://raw.githubusercontent.com/agusnieto77/Sem-UBA/master/seminario.png
favicon: img/favicon.ico
show_downloads: false
