---
output: md_document
---

# Bibliografía

[Responsables de lecturas](https://docs.google.com/spreadsheets/d/1daRYQMJXmObIAJEE3GKJkB89YuvCS28P4jiMcUdkSIU/edit?usp=sharing "Formulario")

## Unidad I

### Obligatoria

-   Tilly, C. (1973) Computers in Historical Analysis. Computers and the Humanities, vol. 7, no. 6,  pp. 323–35.  ([link](https://sci-hub.se/https://www.jstor.org/stable/30199589 "Computers in Historical Analysis")).


-   Gualda, Estrella (2022) Social big data, sociología y ciencias sociales computacionales. *Empiria: Revista de metodología de ciencias sociales*, 53, 147-177  ([link](https://revistas.uned.es/index.php/empiria/article/view/32631/24825 "Social big data, sociología y ciencias sociales computacionales")).

-   Putnam, Lara (2016) The Transnational and the Text-searchable: Digitized Sources and the Shadows they Cast, *American Historical Review*, vol. 121, 2, 2016.

## Unidad II

### Obligatoria

-   Albrieu, Ramiro & Palazzo, Gabriel (2020) Categorización de conflictos sociales en el ámbito de los recursos naturales: Un estudio de las actividades extractivas mediante la minería de textos. Revista CEPAL, 131, 29--59 ([link](https://repositorio.cepal.org/bitstream/handle/11362/45952/RVE131_Albrieu.pdf?sequence=1&isAllowed=y "Categorización de conflictos sociales en el ámbito de los recursos naturales")).

-   Franzosi, Roberto (2020) What's in a text? Bridging the gap between quality and quantity in the digital era. Quality & Quantity, 1-28 ([link](https://sci-hub.se/https://doi.org/10.1007/s11135-020-01067-6 "What's in a text?")).

-   Nieto, Agustín, Silvana Ferreyra y Emiliano Calomarde (2022) La pandemia en el pago chico. Agenda mediática y comentarios de lectorxs en Mar del Plata, 2020-2021. Ferrari, Marcela *Memorias del COVID. Partido de General Pueyrredon, 2020 - 2021*, Rosario: Prohistoria ([link](https://www.academia.edu/77606214/TIEMPOS_DE_PANDEMIA "La pandemia en el pago chico")).

-   Liang, H., & Zhu, J. J. (2017). Big data, collection of (social media, harvesting). The International Encyclopedia of Communication Research Methods, 1--18 ([link](https://sci-hub.se/https://doi.org/10.1002/9781118901731.iecrm0015 "Big data, collection of (social media, harvesting)")).

-   Escobar, M., Gil Moreno, E., & Calvo López, C. (2022). Análisis de la dinámica, la estructura y el contenido de los mensajes de Twitter: violencia sexual en #Cuéntalo. Empiria. Revista De metodología De Ciencias Sociales, (53), 89–119) ([link](https://revistas.uned.es/index.php/empiria/article/view/32614/25534 "Análisis de la dinámica, la estructura y el contenido de los mensajes de Twitter")).

## Unidad III

### Obligatoria

-   Müller, Kirill & Wickham, Hadley (2022) Tibble: Simple data frames ([link](https://cran.r-project.org/web/packages/tibble/tibble.pdf "Tibble")).

- Trezza D (2023) To scrape or not to scrape, this is dilemma. The post-API scenario and implications on digital research. Front. Sociol. 8:1145038 ([link](https://www.frontiersin.org/articles/10.3389/fsoc.2023.1145038/full "To scrape or not to scrape")).

-   Wickham, Hadley (2021) *Rvest: easily harvest (scrape) web pages* ([link](https://cran.r-project.org/web/packages/rvest/rvest.pdf "easily harvest (scrape) web pages")).

-   Wickham, Hadley & Cia. (2019) Welcome to the tidyverse. *Journal of Open Source Software*, 4(43), 1686 ([link](https://doi.org/10.21105/joss.01686 "Welcome to the tidyverse")).

## Unidad IV

### Obligatoria

-   Donig, S., Eckl, M., Gassner, S., & Rehbein, M. (2023). Web archive analytics: Blind spots and silences in distant readings of the archived web. Digital Scholarship in the Humanities ([link](https://doi.org/10.1093/llc/fqad014 "Web archive analytics")).

-   Melo, Jairo (2017) Lectura distante, fragmentada y colaborativa en el archivo infinito. *Relaciones: Estudios de historia y sociedad*, 38,149, 169-89 ([link](https://www.scielo.org.mx/pdf/rz/v38n149/2448-7554-rz-38-149-00169.pdf "Lectura distante, fragmentada y colaborativa en el archivo infinito")).

-   Moretti, Franco (2015) El matadero de la literatura. *Lectura distant*e, FCE, Buenos Aires ([link](https://github.com/agusnieto77/Sem-UBA/raw/master/bibliograf%C3%ADa/Moretti%20-%20El%20matadero%20de%20la%20literatura%20III.pdf "El matadero de la literatura")).

-   Mueller, Martin (2012) Scalable Reading. *Scalablereading* ([link](https://scalablereading.northwestern.edu/?page_id=22 "Scalable Reading")).

## Unidad V

### Obligatoria

-   Cairo, Alberto (2017) Visualización de datos: una imagen puede valer más que mil números, pero no siempre más que mil palabras. *Profesional de la información* 26, 6, 1025-28
([link](https://doi.org/10.3145/epi.2017.nov.02 "Visualización de datos")).

-   Moretti, Franco (2023) Ver y no ver. Sobre la visualización de los datos en las disciplinas humanísticas. *Falso movimiento*, 65-101
([link](https://doi.org/10.51829/Drassana.28.650 "Ver y no ver")).

-   Rosati, German (2020) La visualización de datos es trabajo esencial. Factor\~data (blog), *Medium* ([link](https://medium.com/factor-data/la-visualizaci%C3%B3n-de-datos-es-trabajo-esencial-ea7acc20b5d3 "La visualización de datos es trabajo esencial")).

-   Tufte, Edward (2001) Estética y Técnica en el Diseño de Gráficos de Datos. *La Representación Visual de Información Cuantitativa*, 177-190
([link](https://medium.com/factor-data/la-visualizaci%C3%B3n-de-datos-es-trabajo-esencial-ea7acc20b5d3 "Estética y Técnica en el Diseño de Gráficos de Datos")).
